name: mini_project_10
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  firebase_core: 2.27.2
  cloud_firestore: 4.15.10
  firebase_storage: 11.6.11
  get_storage: 2.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^11.0.0
  flutter_timezone: ^1.0.8
  timezone: ^0.9.2
  flutter_screenutil: ^5.9.0
  image_picker: ^1.1.1
  palette_generator: ^0.3.3+3
  uuid: ^3.0.6
  firebase_auth: ^4.18.0
  flutter_svg: ^1.0.0
  google_fonts: ^6.2.1
  sqflite: ^2.3.3+1
  email_validator: ^2.1.17

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo2.png
  color_dark: "#121212"
  image_dark: assets/images/logo2.png
  android_12:
    image: assets/images/logo2.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo2.png
    icon_background_color_dark: "#121212"
  web: false
